sonar.projectKey=thevilpanda_DB-Creator
sonar.organization=thevilpanda
sonar.projectName=DB Creator

sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/.venv/**,**/migrations/**,**/dist/**,**/__pycache__/**

sonar.python.version=3
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
